apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::681363386678:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LD4JBGCQ324S
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::681363386678:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-02T08:21:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "180078"
  uid: 04efb279-c042-45b4-b046-4a699d0d3d59
